title: "CyberConforme"
description: "Cybersécurité & Conformité simplifiées"
theme: jekyll-theme-slate
sass:
  style: compressed
nav:
  - name: "Accueil"
    link: /
  - name: "Blog"
    link: /blog
  - name: "À propos"
    link: /about
  - name: "Contact"
    link: /#contact
logo: /assets/images/logo.png
favicon: /favicon.ico
